
# for better compatiable with philly and potential running enviroment
# all path under path should be rel_path w.r.t the config.py
# and the abspath will be compute when finalize

# python -m torch.distributed.launch  --nproc_per_node=2 main.py  --setting naive_raw.yaml
# --config trainer.default.log_step=1 trainer.default.sample_step=20

device: 1

batch_size: 16
num_workers: 4
epochs: 90

lr: 0.1
weight_decay: 0.0005
momentum: 0.9
decay_epochs: [30, 60, 80]
dataset_path: /home/yoon/data/face_ocular

model: resnet18

net_module: ocular_ckdnet
network: CKDNetwork_ocular
dataset: ocular
distill: both
batchnorm: shared

face_distill: True
ocular_distill: True

alpha: 0.9
tau: 2.5

result_path: ./results/

